events {
    worker_connections 1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;
    
    sendfile        on;
    keepalive_timeout  65;

    server {
        listen       80;
        server_name  localhost;

        # Authentication Service
        location /authentication/ {
            proxy_pass http://host.docker.internal:4001/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # Project Management Service
        location /project-management/ {
            proxy_pass http://host.docker.internal:4002/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # Task Management Service
        location /task-management/ {
            proxy_pass http://host.docker.internal:4003/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # Notifications Service (WebSockets)
        location /ws/ {
            proxy_pass http://host.docker.internal:4004/;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "Upgrade";
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location / {
            return 200 'Nginx API Gateway is running.';
            add_header Content-Type text/plain;
        }
        
        error_page   500 502 503 504  /50x.html;
    }
}
